services:
  node-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_ENGINE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=my_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - NODE_ENV=development
    volumes:
      - ./:/app
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_api
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
