services:
  node-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_ENGINE=sqlite
      - SQLITE_STORAGE=/var/data/database.sqlite
      - NODE_ENV=development
    volumes:
      - ./:/app
      - sqlite_data:/var/data
    command: npm run dev

volumes:
  sqlite_data:

  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=my_api
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "5050:80"

  # mysqul:
  #   image: mysql:5
  #   environment:
  #     - MYSQL_DATABASE=my_api
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - MYSQL_PORT=3306
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80
